Blacklistusers = {
  "Ceroggez",
  "NomisFinalStand",
  "JLennonHD_Gamer",
  "DONOVAVN100",
  "mandird17",
  "iiTr4xshXrSweaty",
  "firesperet55",
  "TheOneRisingAboveAIl",
  "Nev3rH3ard87",
  "Oni_akumon",
  "condori147",
  "TheGodRisingAboveAll",
  "iiTr4xshXrSweaty",
}
